# Generated by Django 6.0.7 on 2026-09-20 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'مقرر دراسي', 'verbose_name_plural': 'المقررات الدراسية'},
        ),
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'verbose_name': 'ملف عضو هيئة التدريس', 'verbose_name_plural': 'أعضاء هيئة التدريس'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'تخصص أكاديمي', 'verbose_name_plural': 'التخصصات الأكاديمية'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'ملف الطالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='courses.specialization', verbose_name='التخصصات المسندة'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='total_levels',
            field=models.PositiveIntegerField(default=8, help_text='حدد عدد المستويات (مثلاً 8 للبكالوريوس، 4 للدبلوم، 10 للهندسة)', verbose_name='عدد المستويات الدراسية'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_file',
            field=models.FileField(upload_to='courses/', verbose_name='ملف المقرر / التوصيف'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='توصيف المقرر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.doctorprofile', verbose_name='أستاذ المقرر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='رقم المستوى'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم المقرر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.specialization', verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='الرقم الوظيفي / الأكاديمي'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_doctors', to='courses.specialization', verbose_name='التخصص الأساسي'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم التخصص'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='رقم المستوى'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='courses.specialization', verbose_name='التخصص الأكاديمي'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='university_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='الرقم الجامعي'),
        ),
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='رقم المستوى')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المستوى')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='courses.specialization', verbose_name='التخصص الأكاديمي')),
            ],
            options={
                'verbose_name': 'مستوى دراسي',
                'verbose_name_plural': 'المستويات الدراسية',
                'ordering': ['specialization', 'number'],
                'unique_together': {('specialization', 'number')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='academic_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.academiclevel', verbose_name='المستوى الأكاديمي'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='courses.academiclevel', verbose_name='المستوى الدراسي'),
        ),
    ]
