# Generated by Django 6.0.7 on 2026-09-20 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_alter_doctorprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='academic_level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='academic_level',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='total_levels',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_file',
            field=models.FileField(upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.specialization'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='courses.specialization'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='courses.specialization'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='university_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField(default=1)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='courses.specialization')),
            ],
            options={
                'ordering': ['specialization', 'number'],
                'unique_together': {('specialization', 'number')},
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql="UPDATE courses_course SET level = NULL; UPDATE courses_studentprofile SET level = NULL;",
            reverse_sql=""
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.level'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='courses.level'),
        ),
        migrations.DeleteModel(
            name='AcademicLevel',
        ),
    ]
